[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "boto3>=1.37.29",
    "botocore>=1.37.29",
    "fastapi>=0.115.6",
    "mcp>=1.6.0",
    "openai>=1.75.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "streamlit>=1.41.1",
    "streamlit-cookies-controller>=0.0.4",
    "streamlit-local-storage>=0.0.25",
    "tzdata>=2024.2",
    "uvicorn>=0.34.0",
    "gradio>=5.0.0",
    "imaplib2>=3.6",
    "email-validator>=2.1.0",
]
